create table proj.geo_classes (
  id integer generated by default as identity primary key,

  parent_id integer null
    references proj.geo_classes(id)
    on delete restrict,

  code text null,
  name text not null,
  layer smallint not null,

  remark text null,

  sort_order integer not null default 0,
  is_disabled boolean not null default false,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint ck_geo_classes_name_not_blank
    check (btrim(name) <> ''),

  constraint ck_geo_classes_code_not_blank
    check (code is null or btrim(code) <> ''),

  constraint ck_geo_classes_layer
    check (layer >= 1),

  constraint ck_geo_classes_not_self_parent
    check (parent_id is null or parent_id <> id)
);

create unique index uq_geo_classes_code
  on proj.geo_classes(code)
  where code is not null;

create index idx_geo_classes_parent_id
  on proj.geo_classes(parent_id);

create index idx_geo_classes_layer
  on proj.geo_classes(layer);


drop table proj.geo_rock_classes cascade;
create table proj.geo_rock_classes (
  id smallint generated by default as identity primary key,

  code text not null unique,
  name text not null unique,
  remark text null,

  sort_order smallint not null default 0,
  is_disabled boolean not null default false,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

insert into proj.geo_rock_classes (
  code,
  name,
  sort_order
)
values
  ('I',     '一类围岩', 1),
  ('II',    '二类围岩', 2),
  ('III',   '三类围岩', 3),
  ('IV',    '四类围岩', 4),
  ('V',     '五类围岩', 5),
  ('VI',    '六类围岩', 6)
on conflict (code) do update
set
  name = excluded.name,
  remark = excluded.remark,
  sort_order = excluded.sort_order,
  updated_at = now();



create table proj.tunnel_risks (
  id uuid primary key default gen_random_uuid(),

  tunnel_id uuid not null
    references proj.tunnels(id)
    on delete cascade,

  name text not null,

  geo_class_id integer null
    references proj.geo_classes(id)
    on delete restrict,

  geo_rock_class_id smallint null
    references proj.geo_rock_classes(id)
    on delete restrict,

  risk_level smallint not null default 1,

  start_chainage numeric(12, 3),
  end_chainage numeric(12, 3),
  burial_depth numeric(10, 3),

  description text,
  remark text,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz
);


insert into proj.tunnel_risks (
  tunnel_id,
  name,

  start_chainage,
  end_chainage,
  burial_depth,  

  geo_class_id,
  geo_rock_class_id,

  description,
  remark,
  risk_level

)
values (
  '37ff60d8-ea47-4c24-b22d-e1b7666a7e07'::uuid,
  '侧穿万畅自行车项目基础施工风险',

  10.000,
  200.000,
  19.650,

  343,
  6,  

  '深大城际盾构于左线里程I33+500DK33+700范围侧穿万畅地块基础，基坑采用中12000950合围护结构。覆土厚度约45.95m。距围护结构最小水平距离约为20.33m，最小竖向距离约为19.65m。穿越地层为微风化花岗岩。',
  null,
  4

);


create table if not exists proj.risk_solutions (
  id uuid primary key default gen_random_uuid(),

  code text null,
  name text not null,

  applicable_conditions text null,
  summary text null,

  source_risk_id uuid null
    references proj.tunnel_risks(id)
    on delete set null,

  remark text null,

  is_template boolean not null default false,
  is_disabled boolean not null default false,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint ck_risk_solutions_name_not_blank
    check (btrim(name) <> ''),

  constraint ck_risk_solutions_code_not_blank
    check (code is null or btrim(code) <> '')
);

create unique index if not exists uq_risk_solutions_code
  on proj.risk_solutions(code)
  where code is not null;


create table if not exists proj.risk_solution_items (
  id uuid primary key default gen_random_uuid(),

  solution_id uuid not null
    references proj.risk_solutions(id)
    on delete cascade,

  item_no smallint not null,
  title text null,
  content text not null,

  category text null,

  is_required boolean not null default true,
  sort_order smallint not null default 0,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint uq_risk_solution_items_no
    unique (solution_id, item_no),

  constraint ck_risk_solution_items_content_not_blank
    check (btrim(content) <> ''),

  constraint ck_risk_solution_items_item_no
    check (item_no > 0)
);

create or replace view app.v_tunnel_risks_active
with (security_invoker = true)
as
with active_assignments as (
  select distinct on (ta.tunnel_id)
    ta.tunnel_id,
    ta.tbm_id,
    ta.start_date
  from tbm.tbm_assignments ta
  where ta.end_date is null
  order by
    ta.tunnel_id,
    ta.start_date desc nulls last
)
select
  risk.id as risk_id,

  risk.tunnel_id,
  aa.tbm_id,
  

  risk.name as risk_name,
  risk.risk_level,

  risk.start_chainage,
  risk.end_chainage,
  tunnel.advance_direction,

  risk.burial_depth,


  risk.geo_class_id,
  geo.name as geo_class_name,
  geo.layer as geo_class_layer,

  risk.geo_rock_class_id,
  rock.code as geo_rock_class_code,
  rock.name as geo_rock_class_name,

  risk.description,
  risk.remark,

  coalesce(solution_data.solutions, '[]'::jsonb) as solutions,

  risk.created_at,
  risk.updated_at

from active_assignments aa

join proj.tunnel_risks risk
  on risk.tunnel_id = aa.tunnel_id
 and risk.deleted_at is null

join proj.tunnels tunnel
  on tunnel.id = risk.tunnel_id
 and tunnel.deleted_at is null

left join proj.geo_classes geo
  on geo.id = risk.geo_class_id

left join proj.geo_rock_classes rock
  on rock.id = risk.geo_rock_class_id

left join lateral (
  select
    jsonb_agg(
      jsonb_build_object(
        'id', solution.id,
        'code', solution.code,
        'name', solution.name,
        'applicableConditions', solution.applicable_conditions,
        'summary', solution.summary,
        'isPrimary', relation.is_primary,
        'items', coalesce(item_data.items, '[]'::jsonb)
      )
      order by
        relation.is_primary desc,
        solution.created_at,
        solution.id
    ) as solutions

  from proj.tunnel_risk_solutions relation

  join proj.risk_solutions solution
    on solution.id = relation.solution_id
   and solution.is_disabled = false

  left join lateral (
    select
      jsonb_agg(
        jsonb_build_object(
          'id', item.id,
          'itemNo', item.item_no,
          'title', item.title,
          'content', item.content,
          'category', item.category,
          'isRequired', item.is_required
        )
        order by
          item.sort_order,
          item.item_no,
          item.id
      ) as items
    from proj.risk_solution_items item
    where item.solution_id = solution.id
  ) item_data on true

  where relation.risk_id = risk.id
) solution_data on true;