create table proj.geo_classes (
  id integer generated by default as identity primary key,

  parent_id integer null
    references proj.geo_classes(id)
    on delete restrict,

  code text null,
  name text not null,
  layer smallint not null,

  remark text null,

  sort_order integer not null default 0,
  is_disabled boolean not null default false,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint ck_geo_classes_name_not_blank
    check (btrim(name) <> ''),

  constraint ck_geo_classes_code_not_blank
    check (code is null or btrim(code) <> ''),

  constraint ck_geo_classes_layer
    check (layer >= 1),

  constraint ck_geo_classes_not_self_parent
    check (parent_id is null or parent_id <> id)
);

create unique index uq_geo_classes_code
  on proj.geo_classes(code)
  where code is not null;

create index idx_geo_classes_parent_id
  on proj.geo_classes(parent_id);

create index idx_geo_classes_layer
  on proj.geo_classes(layer);


create table proj.geo_rock_classes (
  id smallint generated by default as identity primary key,

  code text not null unique,
  name text not null unique,
  remark text null,

  sort_order smallint not null default 0,
  is_disabled boolean not null default false,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);


create table proj.tunnel_risks (
  id uuid primary key default gen_random_uuid(),

  tunnel_id uuid not null
    references proj.tunnels(id)
    on delete cascade,

  name text not null,

  geo_class_id integer null
    references proj.geo_classes(id)
    on delete restrict,

  geo_rock_class_id smallint null
    references proj.geo_rock_classes(id)
    on delete restrict,

  risk_level smallint not null default 1,

  start_chainage numeric(12, 3),
  end_chainage numeric(12, 3),
  burial_depth numeric(10, 3),

  description text,
  remark text,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz
);